<a href="https://colab.research.google.com/github/KarolSalazar/tareas_de_clase/blob/master/bases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#para usar pandas en colab
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
Ruta = '/content/drive/MyDrive/1553768847-housing.csv'

In [10]:
db = pd.read_csv(Ruta)
display(db)


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                  41          880           129.0   
1        -122.22     37.86                  21         7099          1106.0   
2        -122.24     37.85                  52         1467           190.0   
3        -122.25     37.85                  52         1274           235.0   
4        -122.25     37.85                  52         1627           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                  25         1665           374.0   
20636    -121.21     39.49                  18          697           150.0   
20637    -121.22     39.43                  17         2254           485.0   
20638    -121.32     39.43                  18         1860           409.0   
20639    -121.24     39.37                  16         2785           616.0   

       population  households  median_income ocean_proximity  \
0             322         126         8.3252        NEAR BAY   
1            2401        1138         8.3014        NEAR BAY   
2             496         177         7.2574        NEAR BAY   
3             558         219         5.6431        NEAR BAY   
4             565         259         3.8462        NEAR BAY   
...           ...         ...            ...             ...   
20635         845         330         1.5603          INLAND   
20636         356         114         2.5568          INLAND   
20637        1007         433         1.7000          INLAND   
20638         741         349         1.8672          INLAND   
20639        1387         530         2.3886          INLAND   

       median_house_value  
0                  452600  
1                  358500  
2                  352100  
3                  341300  
4                  342200  
...                   ...  
20635               78100  
20636               77100  
20637               92300  
20638               84700  
20639               89400  

[20640 rows x 10 columns]

In [11]:
db.head(12)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0     -122.23     37.88                  41          880           129.0   
1     -122.22     37.86                  21         7099          1106.0   
2     -122.24     37.85                  52         1467           190.0   
3     -122.25     37.85                  52         1274           235.0   
4     -122.25     37.85                  52         1627           280.0   
5     -122.25     37.85                  52          919           213.0   
6     -122.25     37.84                  52         2535           489.0   
7     -122.25     37.84                  52         3104           687.0   
8     -122.26     37.84                  42         2555           665.0   
9     -122.25     37.84                  52         3549           707.0   
10    -122.26     37.85                  52         2202           434.0   
11    -122.26     37.85                  52         3503           752.0   

    population  households  median_income ocean_proximity  median_house_value  
0          322         126         8.3252        NEAR BAY              452600  
1         2401        1138         8.3014        NEAR BAY              358500  
2          496         177         7.2574        NEAR BAY              352100  
3          558         219         5.6431        NEAR BAY              341300  
4          565         259         3.8462        NEAR BAY              342200  
5          413         193         4.0368        NEAR BAY              269700  
6         1094         514         3.6591        NEAR BAY              299200  
7         1157         647         3.1200        NEAR BAY              241400  
8         1206         595         2.0804        NEAR BAY              226700  
9         1551         714         3.6912        NEAR BAY              261100  
10         910         402         3.2031        NEAR BAY              281500  
11        1504         734         3.2705        NEAR BAY              241800

In [12]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  int64  
 3   total_rooms         20640 non-null  int64  
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  int64  
 6   households          20640 non-null  int64  
 7   median_income       20640 non-null  float64
 8   ocean_proximity     20640 non-null  object 
 9   median_house_value  20640 non-null  int64  
dtypes: float64(4), int64(5), object(1)
memory usage: 1.6+ MB


In [ ]:
db.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [ ]:
db.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity', 'median_house_value'],
      dtype='object')

In [ ]:
db[['total_rooms','households']]

total_rooms  households
0              880         126
1             7099        1138
2             1467         177
3             1274         219
4             1627         259
...            ...         ...
20635         1665         330
20636          697         114
20637         2254         433
20638         1860         349
20639         2785         530

[20640 rows x 2 columns]

In [ ]:
pd.unique(db['total_rooms'])
db['total_rooms']=db['total_rooms'].replace(1627,2003)
db

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                  41          880           129.0   
1        -122.22     37.86                  21         7099          1106.0   
2        -122.24     37.85                  52         1467           190.0   
3        -122.25     37.85                  52         1274           235.0   
4        -122.25     37.85                  52         2003           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                  25         1665           374.0   
20636    -121.21     39.49                  18          697           150.0   
20637    -121.22     39.43                  17         2254           485.0   
20638    -121.32     39.43                  18         1860           409.0   
20639    -121.24     39.37                  16         2785           616.0   

       population  households  median_income ocean_proximity  \
0             322         126         8.3252        NEAR BAY   
1            2401        1138         8.3014        NEAR BAY   
2             496         177         7.2574        NEAR BAY   
3             558         219         5.6431        NEAR BAY   
4             565         259         3.8462        NEAR BAY   
...           ...         ...            ...             ...   
20635         845         330         1.5603          INLAND   
20636         356         114         2.5568          INLAND   
20637        1007         433         1.7000          INLAND   
20638         741         349         1.8672          INLAND   
20639        1387         530         2.3886          INLAND   

       median_house_value  
0                  452600  
1                  358500  
2                  352100  
3                  341300  
4                  342200  
...                   ...  
20635               78100  
20636               77100  
20637               92300  
20638               84700  
20639               89400  

[20640 rows x 10 columns]

In [ ]:
db[['total_rooms','households']].to_numpy()

array([[ 880,  126],
       [7099, 1138],
       [1467,  177],
       ...,
       [2254,  433],
       [1860,  349],
       [2785,  530]])

In [ ]:
tab =db[['total_rooms','households']].to_numpy()
tab.shape

(20640, 2)

In [ ]:
#se comenzará a usar numpy
import numpy as np

In [ ]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.arange(8,67,3)

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56,
       59, 62, 65])

In [ ]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [ ]:
np.logspace(0,100,5)
#desde comienza 10 elevado a la 0
#10 elevado a la 100
#con espaciado logaritmico

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

Tarea:

-conseguir una base de datos con columnas numericas y al menos una str
-hacer un programa que reciba el nombre de un archivo csv en el mismo directorio y que el programa:


1.   retorne el nombre de las columnas y su tipo de datos
2.   Reciba el nombre de una columna str y una numerica
3.   Diga los valores únicos de esa columna
4.   que el usuario pueda ingresar uno de esos valors para filtrar los datos por ese valor
5.   Debe guardar en A los datos numericos sin los valores de esa columna numerica
6.   Debe guardar en Y los datos de esa columna numerica
7.   solucionar sistema AX=Y
8. Exportar la solución en csv o excel


se resuelve en el documento homeworkbases
